// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSongs(t *testing.T) {
	t.Parallel()

	query := Songs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSongsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Songs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSongsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Songs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Songs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSongsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SongSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Songs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSongsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SongExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Song exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SongExists to return true, but got false.")
	}
}

func testSongsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	songFound, err := FindSong(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if songFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSongsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Songs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSongsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Songs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSongsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	songOne := &Song{}
	songTwo := &Song{}
	if err = randomize.Struct(seed, songOne, songDBTypes, false, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}
	if err = randomize.Struct(seed, songTwo, songDBTypes, false, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = songOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = songTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Songs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSongsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	songOne := &Song{}
	songTwo := &Song{}
	if err = randomize.Struct(seed, songOne, songDBTypes, false, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}
	if err = randomize.Struct(seed, songTwo, songDBTypes, false, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = songOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = songTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Songs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func songBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Song) error {
	*o = Song{}
	return nil
}

func songAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Song) error {
	*o = Song{}
	return nil
}

func songAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Song) error {
	*o = Song{}
	return nil
}

func songBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Song) error {
	*o = Song{}
	return nil
}

func songAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Song) error {
	*o = Song{}
	return nil
}

func songBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Song) error {
	*o = Song{}
	return nil
}

func songAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Song) error {
	*o = Song{}
	return nil
}

func songBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Song) error {
	*o = Song{}
	return nil
}

func songAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Song) error {
	*o = Song{}
	return nil
}

func testSongsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Song{}
	o := &Song{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, songDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Song object: %s", err)
	}

	AddSongHook(boil.BeforeInsertHook, songBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	songBeforeInsertHooks = []SongHook{}

	AddSongHook(boil.AfterInsertHook, songAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	songAfterInsertHooks = []SongHook{}

	AddSongHook(boil.AfterSelectHook, songAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	songAfterSelectHooks = []SongHook{}

	AddSongHook(boil.BeforeUpdateHook, songBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	songBeforeUpdateHooks = []SongHook{}

	AddSongHook(boil.AfterUpdateHook, songAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	songAfterUpdateHooks = []SongHook{}

	AddSongHook(boil.BeforeDeleteHook, songBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	songBeforeDeleteHooks = []SongHook{}

	AddSongHook(boil.AfterDeleteHook, songAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	songAfterDeleteHooks = []SongHook{}

	AddSongHook(boil.BeforeUpsertHook, songBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	songBeforeUpsertHooks = []SongHook{}

	AddSongHook(boil.AfterUpsertHook, songAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	songAfterUpsertHooks = []SongHook{}
}

func testSongsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Songs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSongsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(songColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Songs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSongToManyLyrics(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Song
	var b, c Lyric

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, lyricDBTypes, false, lyricColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, lyricDBTypes, false, lyricColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.SongID, a.ID)
	queries.Assign(&c.SongID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Lyrics().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.SongID, b.SongID) {
			bFound = true
		}
		if queries.Equal(v.SongID, c.SongID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SongSlice{&a}
	if err = a.L.LoadLyrics(ctx, tx, false, (*[]*Song)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Lyrics); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Lyrics = nil
	if err = a.L.LoadLyrics(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Lyrics); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testSongToManyTranslations(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Song
	var b, c Translation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, translationDBTypes, false, translationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, translationDBTypes, false, translationColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.SongID, a.ID)
	queries.Assign(&c.SongID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Translations().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.SongID, b.SongID) {
			bFound = true
		}
		if queries.Equal(v.SongID, c.SongID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SongSlice{&a}
	if err = a.L.LoadTranslations(ctx, tx, false, (*[]*Song)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Translations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Translations = nil
	if err = a.L.LoadTranslations(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Translations); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testSongToManyAddOpLyrics(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Song
	var b, c, d, e Lyric

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, songDBTypes, false, strmangle.SetComplement(songPrimaryKeyColumns, songColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Lyric{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, lyricDBTypes, false, strmangle.SetComplement(lyricPrimaryKeyColumns, lyricColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Lyric{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddLyrics(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.SongID) {
			t.Error("foreign key was wrong value", a.ID, first.SongID)
		}
		if !queries.Equal(a.ID, second.SongID) {
			t.Error("foreign key was wrong value", a.ID, second.SongID)
		}

		if first.R.Song != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Song != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Lyrics[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Lyrics[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Lyrics().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSongToManySetOpLyrics(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Song
	var b, c, d, e Lyric

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, songDBTypes, false, strmangle.SetComplement(songPrimaryKeyColumns, songColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Lyric{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, lyricDBTypes, false, strmangle.SetComplement(lyricPrimaryKeyColumns, lyricColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetLyrics(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Lyrics().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetLyrics(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Lyrics().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SongID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SongID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.SongID) {
		t.Error("foreign key was wrong value", a.ID, d.SongID)
	}
	if !queries.Equal(a.ID, e.SongID) {
		t.Error("foreign key was wrong value", a.ID, e.SongID)
	}

	if b.R.Song != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Song != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Song != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Song != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Lyrics[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Lyrics[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testSongToManyRemoveOpLyrics(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Song
	var b, c, d, e Lyric

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, songDBTypes, false, strmangle.SetComplement(songPrimaryKeyColumns, songColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Lyric{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, lyricDBTypes, false, strmangle.SetComplement(lyricPrimaryKeyColumns, lyricColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddLyrics(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Lyrics().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveLyrics(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Lyrics().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SongID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SongID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Song != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Song != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Song != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Song != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Lyrics) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Lyrics[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Lyrics[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testSongToManyAddOpTranslations(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Song
	var b, c, d, e Translation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, songDBTypes, false, strmangle.SetComplement(songPrimaryKeyColumns, songColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Translation{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, translationDBTypes, false, strmangle.SetComplement(translationPrimaryKeyColumns, translationColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Translation{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddTranslations(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.SongID) {
			t.Error("foreign key was wrong value", a.ID, first.SongID)
		}
		if !queries.Equal(a.ID, second.SongID) {
			t.Error("foreign key was wrong value", a.ID, second.SongID)
		}

		if first.R.Song != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Song != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Translations[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Translations[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Translations().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSongToManySetOpTranslations(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Song
	var b, c, d, e Translation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, songDBTypes, false, strmangle.SetComplement(songPrimaryKeyColumns, songColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Translation{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, translationDBTypes, false, strmangle.SetComplement(translationPrimaryKeyColumns, translationColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetTranslations(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Translations().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetTranslations(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Translations().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SongID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SongID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.SongID) {
		t.Error("foreign key was wrong value", a.ID, d.SongID)
	}
	if !queries.Equal(a.ID, e.SongID) {
		t.Error("foreign key was wrong value", a.ID, e.SongID)
	}

	if b.R.Song != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Song != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Song != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Song != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Translations[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Translations[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testSongToManyRemoveOpTranslations(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Song
	var b, c, d, e Translation

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, songDBTypes, false, strmangle.SetComplement(songPrimaryKeyColumns, songColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Translation{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, translationDBTypes, false, strmangle.SetComplement(translationPrimaryKeyColumns, translationColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddTranslations(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Translations().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveTranslations(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Translations().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.SongID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.SongID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Song != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Song != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Song != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Song != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Translations) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Translations[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Translations[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testSongsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSongsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SongSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSongsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Songs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	songDBTypes = map[string]string{`ID`: `integer`, `Title`: `character varying`, `Anime`: `character varying`, `Released`: `timestamp without time zone`}
	_           = bytes.MinRead
)

func testSongsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(songPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(songAllColumns) == len(songPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Songs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, songDBTypes, true, songPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSongsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(songAllColumns) == len(songPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Song{}
	if err = randomize.Struct(seed, o, songDBTypes, true, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Songs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, songDBTypes, true, songPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(songAllColumns, songPrimaryKeyColumns) {
		fields = songAllColumns
	} else {
		fields = strmangle.SetComplement(
			songAllColumns,
			songPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SongSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSongsUpsert(t *testing.T) {
	t.Parallel()

	if len(songAllColumns) == len(songPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Song{}
	if err = randomize.Struct(seed, &o, songDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Song: %s", err)
	}

	count, err := Songs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, songDBTypes, false, songPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Song: %s", err)
	}

	count, err = Songs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
