// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTranslations(t *testing.T) {
	t.Parallel()

	query := Translations()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTranslationsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Translations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTranslationsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Translations().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Translations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTranslationsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TranslationSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Translations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTranslationsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TranslationExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Translation exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TranslationExists to return true, but got false.")
	}
}

func testTranslationsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	translationFound, err := FindTranslation(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if translationFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTranslationsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Translations().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTranslationsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Translations().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTranslationsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	translationOne := &Translation{}
	translationTwo := &Translation{}
	if err = randomize.Struct(seed, translationOne, translationDBTypes, false, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}
	if err = randomize.Struct(seed, translationTwo, translationDBTypes, false, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = translationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = translationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Translations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTranslationsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	translationOne := &Translation{}
	translationTwo := &Translation{}
	if err = randomize.Struct(seed, translationOne, translationDBTypes, false, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}
	if err = randomize.Struct(seed, translationTwo, translationDBTypes, false, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = translationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = translationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Translations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func translationBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Translation) error {
	*o = Translation{}
	return nil
}

func translationAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Translation) error {
	*o = Translation{}
	return nil
}

func translationAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Translation) error {
	*o = Translation{}
	return nil
}

func translationBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Translation) error {
	*o = Translation{}
	return nil
}

func translationAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Translation) error {
	*o = Translation{}
	return nil
}

func translationBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Translation) error {
	*o = Translation{}
	return nil
}

func translationAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Translation) error {
	*o = Translation{}
	return nil
}

func translationBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Translation) error {
	*o = Translation{}
	return nil
}

func translationAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Translation) error {
	*o = Translation{}
	return nil
}

func testTranslationsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Translation{}
	o := &Translation{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, translationDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Translation object: %s", err)
	}

	AddTranslationHook(boil.BeforeInsertHook, translationBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	translationBeforeInsertHooks = []TranslationHook{}

	AddTranslationHook(boil.AfterInsertHook, translationAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	translationAfterInsertHooks = []TranslationHook{}

	AddTranslationHook(boil.AfterSelectHook, translationAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	translationAfterSelectHooks = []TranslationHook{}

	AddTranslationHook(boil.BeforeUpdateHook, translationBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	translationBeforeUpdateHooks = []TranslationHook{}

	AddTranslationHook(boil.AfterUpdateHook, translationAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	translationAfterUpdateHooks = []TranslationHook{}

	AddTranslationHook(boil.BeforeDeleteHook, translationBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	translationBeforeDeleteHooks = []TranslationHook{}

	AddTranslationHook(boil.AfterDeleteHook, translationAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	translationAfterDeleteHooks = []TranslationHook{}

	AddTranslationHook(boil.BeforeUpsertHook, translationBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	translationBeforeUpsertHooks = []TranslationHook{}

	AddTranslationHook(boil.AfterUpsertHook, translationAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	translationAfterUpsertHooks = []TranslationHook{}
}

func testTranslationsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Translations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTranslationsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(translationColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Translations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTranslationToManyLyrics(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Translation
	var b, c Lyric

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, lyricDBTypes, false, lyricColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, lyricDBTypes, false, lyricColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.TranslationID, a.ID)
	queries.Assign(&c.TranslationID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Lyrics().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.TranslationID, b.TranslationID) {
			bFound = true
		}
		if queries.Equal(v.TranslationID, c.TranslationID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := TranslationSlice{&a}
	if err = a.L.LoadLyrics(ctx, tx, false, (*[]*Translation)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Lyrics); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Lyrics = nil
	if err = a.L.LoadLyrics(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Lyrics); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testTranslationToManyAddOpLyrics(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Translation
	var b, c, d, e Lyric

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, translationDBTypes, false, strmangle.SetComplement(translationPrimaryKeyColumns, translationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Lyric{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, lyricDBTypes, false, strmangle.SetComplement(lyricPrimaryKeyColumns, lyricColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Lyric{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddLyrics(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.TranslationID) {
			t.Error("foreign key was wrong value", a.ID, first.TranslationID)
		}
		if !queries.Equal(a.ID, second.TranslationID) {
			t.Error("foreign key was wrong value", a.ID, second.TranslationID)
		}

		if first.R.Translation != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Translation != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Lyrics[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Lyrics[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Lyrics().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testTranslationToManySetOpLyrics(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Translation
	var b, c, d, e Lyric

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, translationDBTypes, false, strmangle.SetComplement(translationPrimaryKeyColumns, translationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Lyric{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, lyricDBTypes, false, strmangle.SetComplement(lyricPrimaryKeyColumns, lyricColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetLyrics(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Lyrics().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetLyrics(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Lyrics().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.TranslationID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.TranslationID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.TranslationID) {
		t.Error("foreign key was wrong value", a.ID, d.TranslationID)
	}
	if !queries.Equal(a.ID, e.TranslationID) {
		t.Error("foreign key was wrong value", a.ID, e.TranslationID)
	}

	if b.R.Translation != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Translation != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Translation != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Translation != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Lyrics[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Lyrics[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testTranslationToManyRemoveOpLyrics(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Translation
	var b, c, d, e Lyric

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, translationDBTypes, false, strmangle.SetComplement(translationPrimaryKeyColumns, translationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Lyric{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, lyricDBTypes, false, strmangle.SetComplement(lyricPrimaryKeyColumns, lyricColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddLyrics(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Lyrics().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveLyrics(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Lyrics().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.TranslationID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.TranslationID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Translation != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Translation != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Translation != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Translation != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Lyrics) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Lyrics[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Lyrics[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testTranslationToOneSongUsingSong(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Translation
	var foreign Song

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, songDBTypes, false, songColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Song struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.SongID, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Song().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddSongHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Song) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := TranslationSlice{&local}
	if err = local.L.LoadSong(ctx, tx, false, (*[]*Translation)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Song == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Song = nil
	if err = local.L.LoadSong(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Song == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testTranslationToOneSetOpSongUsingSong(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Translation
	var b, c Song

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, translationDBTypes, false, strmangle.SetComplement(translationPrimaryKeyColumns, translationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, songDBTypes, false, strmangle.SetComplement(songPrimaryKeyColumns, songColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, songDBTypes, false, strmangle.SetComplement(songPrimaryKeyColumns, songColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Song{&b, &c} {
		err = a.SetSong(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Song != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Translations[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.SongID, x.ID) {
			t.Error("foreign key was wrong value", a.SongID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.SongID))
		reflect.Indirect(reflect.ValueOf(&a.SongID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.SongID, x.ID) {
			t.Error("foreign key was wrong value", a.SongID, x.ID)
		}
	}
}

func testTranslationToOneRemoveOpSongUsingSong(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Translation
	var b Song

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, translationDBTypes, false, strmangle.SetComplement(translationPrimaryKeyColumns, translationColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, songDBTypes, false, strmangle.SetComplement(songPrimaryKeyColumns, songColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetSong(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveSong(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.Song().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.Song != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.SongID) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.Translations) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testTranslationsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTranslationsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TranslationSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTranslationsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Translations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	translationDBTypes = map[string]string{`ID`: `integer`, `SongID`: `integer`, `Title`: `character varying`, `Language`: `character`, `Content`: `jsonb`, `Composers`: `jsonb`, `LyricsFull`: `jsonb`, `Producers`: `jsonb`, `VideoLink`: `text`}
	_                  = bytes.MinRead
)

func testTranslationsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(translationPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(translationAllColumns) == len(translationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Translations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, translationDBTypes, true, translationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTranslationsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(translationAllColumns) == len(translationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Translation{}
	if err = randomize.Struct(seed, o, translationDBTypes, true, translationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Translations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, translationDBTypes, true, translationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(translationAllColumns, translationPrimaryKeyColumns) {
		fields = translationAllColumns
	} else {
		fields = strmangle.SetComplement(
			translationAllColumns,
			translationPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TranslationSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTranslationsUpsert(t *testing.T) {
	t.Parallel()

	if len(translationAllColumns) == len(translationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Translation{}
	if err = randomize.Struct(seed, &o, translationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Translation: %s", err)
	}

	count, err := Translations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, translationDBTypes, false, translationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Translation struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Translation: %s", err)
	}

	count, err = Translations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
