package web
// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

import (
	"the-lyricist/backend/internal/modules/handlers"
	"the-lyricist/backend/internal/modules/repositories"
	"the-lyricist/backend/internal/modules/services"
)

// Injectors from wire.go:

func InitializeSongHandler() *handlers.SongHandler {
	songRepository := repo.NewSongRepository()
	songService := services.NewSongService(songRepository)
	songHandler := handlers.NewSongHandler(songService)
	return songHandler
}

func InitializeTranslationHandler() *handlers.TranslationHandler {
	translationRepository := repo.NewTranslationRepository()
	translationService := services.NewTranslationService(translationRepository)
	translationHandler := handlers.NewTranslationHandler(translationService)
	return translationHandler
}

func InitializeLyricHandler() *handlers.LyricHandler {
	lyricRepository := repo.NewLyricRepository()
	lyricService := services.NewLyricService(lyricRepository)
	lyricHandler := handlers.NewLyricHandler(lyricService)
	return lyricHandler
}
