// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("LyricToSongUsingSong", testLyricToOneSongUsingSong)
	t.Run("LyricToTranslationUsingTranslation", testLyricToOneTranslationUsingTranslation)
	t.Run("TranslationToSongUsingSong", testTranslationToOneSongUsingSong)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("SongToLyrics", testSongToManyLyrics)
	t.Run("SongToTranslations", testSongToManyTranslations)
	t.Run("TranslationToLyrics", testTranslationToManyLyrics)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("LyricToSongUsingLyrics", testLyricToOneSetOpSongUsingSong)
	t.Run("LyricToTranslationUsingLyrics", testLyricToOneSetOpTranslationUsingTranslation)
	t.Run("TranslationToSongUsingTranslations", testTranslationToOneSetOpSongUsingSong)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("LyricToSongUsingLyrics", testLyricToOneRemoveOpSongUsingSong)
	t.Run("LyricToTranslationUsingLyrics", testLyricToOneRemoveOpTranslationUsingTranslation)
	t.Run("TranslationToSongUsingTranslations", testTranslationToOneRemoveOpSongUsingSong)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("SongToLyrics", testSongToManyAddOpLyrics)
	t.Run("SongToTranslations", testSongToManyAddOpTranslations)
	t.Run("TranslationToLyrics", testTranslationToManyAddOpLyrics)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("SongToLyrics", testSongToManySetOpLyrics)
	t.Run("SongToTranslations", testSongToManySetOpTranslations)
	t.Run("TranslationToLyrics", testTranslationToManySetOpLyrics)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("SongToLyrics", testSongToManyRemoveOpLyrics)
	t.Run("SongToTranslations", testSongToManyRemoveOpTranslations)
	t.Run("TranslationToLyrics", testTranslationToManyRemoveOpLyrics)
}
